title: Logic Group at University of Gothenburg
author: G.E. Leigh
email: graham.leigh@gu.se
description: > # this means to ignore newlines until "baseurl:"
  Homepage of the Logic Group at the University of Gothenburg.
  Seminars, projects, etc.

baseurl: "/"
theme: jekyll-theme-slate

collections:
#   seminars:
#     - speaker # date is inferred from file
#     - affil
#     - homepage
#     - title
#     - location
  members:
    order:
      - fredrik.md
      - martin.md
      - rasmus.md
      - bahareh.md
      - graham.md
      - paul.md
    output: true