title: Logic@GU
author: G.E. Leigh
email: graham.leigh@gu.se
description: > # this means to ignore newlines until "baseurl:"
  Homepage of the Logic Group at the University of Gothenburg.

tagline: The logic group at the University of Gothenburg


baseurl: "/"
# theme: jekyll-theme-slate

include:
  - _pages

collections:
  seminars:
    output: true

  # projects:

  members:
    order:
      - fredrik.md
      - martin.md
      - rasmus.md
      - bahareh.md
      - graham.md
      - paul.md
    # output: true