name: webscrape_publications
    
on:
#   push:
#     branches:
#       - main
#       
  schedule:
    - cron: "0 10 * * *" #runs at 00:00 UTC everyday
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
          
      - name: execute py script # run the script to get the latest data
        run: |
          python -m pip install requests pyyaml
          python ./scripts/webscrape_publications.py
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update publication data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  
